[package]
name = "http-api-utils"
version = "0.1.0"
edition = "2021"

[features]
default = ["error_enum", "tokens"]
error_enum = []
tokens = []

[dependencies]
serde_json = "1"

[dependencies.rocket]
version = "0.5.0-rc.3"
features = ["json", "tls"]

